name: Simple_Factions
version: '${project.version}'
main: me.entropire.simple_factions.Simple_Factions
api-version: '1.21.11'
authors: [Entropire]
description: A simple faction plugin ma dan kei hard aangepast door AchilCraft ewaja dude.

commands:
  faction:
  f:
  chat:
    description: Change the chat you type in
  cp:
    description: Change the chat to public
  cf:
    description: Change the chat to faction